<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.7.0-beta</Version>
    <RootNamespace>TGUI</RootNamespace>
    <AssemblyName>tgui.net</AssemblyName>
    <Authors>texus</Authors>
    <Copyright>Copyright © Bruno Van de Velde</Copyright>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>TGUI.Net</PackageId>
    <PackageTags>tgui;sfml;net</PackageTags>
    <Description>TGUI.NET is a .NET binding for the C++ TGUI library to provide a GUI for SFML.Net</Description>
    <PackageLicenseExpression>Zlib</PackageLicenseExpression>
    <PackageProjectUrl>https://tgui.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/texus/TGUI.Net/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIconUrl>https://tgui.eu/resources/NugetIcon.png</PackageIconUrl>
    <PackageIcon>NugetIcon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <None Pack="True" Include="NugetIcon.png" PackagePath="/" />
    <None Pack="True" Include="../README.md" PackagePath="/" />
    <None Pack="True" Include="../CTGUI-runtimes/**" PackagePath="runtimes" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SFML.Net" Version="2.6.0" />
  </ItemGroup>

</Project>
